### ISSUE TITLE
Wrong generation of import statement

### ISSUE THREAD

**Issue by alpet** [labai/labai-jsr305#1]
@NotNull annotation is added before the import declaration and is breaking the compilation. Example

import @NotNull org.w3._2000._09.xmldsig_.TransformType;

**Comment by labai** [comment]
I added some examples with swift xsd, there are no such effect.
What xsd and what java version is used for generation?

**Comment by alpet** [comment]
Hi the xsds I have used are these https://sourceforge.net/p/muleebmsadapter/code/ci/master/tree/src/main/resources/nl/clockwork/mule/ebms/xsd/

**Comment by labai** [comment]
Added an example with those xsd files (https://github.com/labai/labai-jsr305/tree/issue-001/examples/example3-iss1-ebms)
Didn't notice the effect, tried with Java 8, Java 11, Java 17.

**Comment by alpet** [comment]
Interesting, here is the repo that is generating the code. https://github.com/navikt/ebxml-protokoll
Currently the generation is turned off in the pom.xml If you enable it the code will get generated and the problem will manifest.

**Comment by labai** [comment]
your example uses another plugin - **jaxb-maven-plugin**, could you try with **maven-jaxb2-plugin** or **jaxb2-maven-plugin**
